<a href="https://colab.research.google.com/github/muhammadrisma/Data-Science-Python/blob/main/NumPy_Numerical_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NumPy Library***
* NumPy is an open source and free python library for math and computation
* Large number of functions to work with n- dimensional arrays
* NumPy: Numerical Python
* Importing: import numpy as np


In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])

In [5]:
x

array([1, 2, 3, 4, 5])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.random.random(5)

array([0.99617227, 0.13934846, 0.99952778, 0.66976632, 0.96141421])

# ***NumPy 1-D Operations***
* Do math operations for 1-D arrays with NumPy

In [15]:
new_math = np.array([1,2,3])

In [16]:
new_ones = np.ones(3)

In [17]:
new_math + new_ones

array([2., 3., 4.])

In [18]:
new_math * 2

array([2, 4, 6])

In [19]:
new_ones *3

array([3., 3., 3.])

## ***Indexing in NumPy***

In [21]:
new_math = np.array([1,2,3,4,5])

In [27]:
new_math[0]

1

In [28]:
new_math[1]

2

In [29]:
new_math[2]

3

In [30]:
new_math[3]

4

In [31]:
new_math[4]

5

In [32]:
new_math[0] = 10

In [33]:
new_math

array([10,  2,  3,  4,  5])

## ***Math Functions With 1-D Array***

In [36]:
new_math = np.array([1,2,3,4,5])

In [37]:
new_math.min()

1

In [38]:
new_math.max()

5

In [39]:
new_math.mean()

3.0

In [40]:
new_math.sum()

15

In [42]:
new_math.std()

1.4142135623730951

## ***Creating N-D Arrays or Matrices (Multi Dimensional Array)***

In [48]:
x = np.array([[100, 200], [300, 400]])

In [49]:
x

array([[100, 200],
       [300, 400]])

In [58]:
np.ones((3, 4)) #first argument = rows, second argument = columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
np.zeros((3, 4)) #first argument = rows, second argument = columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
np.random.random((3, 4))

array([[0.4057563 , 0.75436272, 0.00778633, 0.9393658 ],
       [0.28602174, 0.20865811, 0.03436309, 0.6582139 ],
       [0.49379802, 0.58708686, 0.61048753, 0.61734277]])