<a href="https://colab.research.google.com/github/muhammadrisma/Data-Science-Python/blob/main/NumPy_Numerical_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NumPy Library***
* NumPy is an open source and free python library for math and computation
* Large number of functions to work with n- dimensional arrays
* NumPy: Numerical Python
* Importing: import numpy as np


In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5])

In [4]:
x

array([1, 2, 3, 4, 5])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.random.random(5)

array([0.88533152, 0.6608117 , 0.06264455, 0.08681182, 0.71027093])

# ***NumPy 1-D Operations***
* Do math operations for 1-D arrays with NumPy

In [8]:
new_math = np.array([1,2,3])

In [9]:
new_ones = np.ones(3)

In [10]:
new_math + new_ones

array([2., 3., 4.])

In [11]:
new_math * 2

array([2, 4, 6])

In [12]:
new_ones *3

array([3., 3., 3.])

## ***Indexing in NumPy***

In [13]:
new_math = np.array([1,2,3,4,5])

In [14]:
new_math[0]

1

In [15]:
new_math[1]

2

In [16]:
new_math[2]

3

In [17]:
new_math[3]

4

In [18]:
new_math[4]

5

In [19]:
new_math[0] = 10

In [20]:
new_math

array([10,  2,  3,  4,  5])

## ***Math Functions With 1-D Array***

In [21]:
new_math = np.array([1,2,3,4,5])

In [22]:
new_math.min()

1

In [24]:
new_math.max()

5

In [25]:
new_math.mean()

3.0

In [26]:
new_math.sum()

15

In [27]:
new_math.std()

1.4142135623730951

## ***Creating N-D Arrays or Matrices (Multi Dimensional Array)***

In [28]:
x = np.array([[100, 200], [300, 400]])

In [29]:
x

array([[100, 200],
       [300, 400]])

In [30]:
np.ones((3, 4)) #first argument = rows, second argument = columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.zeros((3, 4)) #first argument = rows, second argument = columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.random.random((3, 4))

array([[0.87447504, 0.83058007, 0.75801213, 0.41266817],
       [0.34998117, 0.63323073, 0.27873765, 0.47875921],
       [0.44596559, 0.20036558, 0.1859912 , 0.37805198]])

# ***Indexing For Matrices***
* Accesing value: arrayName[row,column]

In [41]:
y = np.array([[2,4],
              [4, 7]])

In [42]:
y[0, 1] #0 is row, 1 is for indexing

4

In [43]:
y[1, 1]

7

In [47]:
y[0:2
  ,1]

array([4])

# ***Reshaping Arays***

In [50]:
new_data = np.array([1,2,3,4,5,6])

In [57]:
new_data.reshape(2, 3) #2 is row, 3 is column


array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
new_data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
x = new_data.reshape(2, 3) 


In [62]:
x[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

## ***Multi Dimensional Array***

In [64]:
x = np.array([[10, 20],[3, 40],[50, 60],[70, 80]])

In [65]:
x

array([[10, 20],
       [ 3, 40],
       [50, 60],
       [70, 80]])

In [66]:
np.ones((5, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [67]:
np.zeros((5, 5, 1))

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])